### ISSUE TITLE
Test the heroku rake running

### ISSUE THREAD

**Issue by TonGarcia** [TonFw/Pinger#8]
The ping will run twice/minute, i think it is good enough.

**TODO**: 
- [x] Must clean the DB everytime it sleep (only while testing);
- [x] Test if it keep the current app alive;
- [x] Create another app (Pinger2) to ping each other;
- [ ] Test/check how much time it is up (based on what is registered on the DB);
- [ ] Check if it sleep even being requested by itself.

**Comment by TonGarcia** [comment]
At 08:29 the apps were sleeping...
Is necessary to check it DataBase to know what happened,but I think Pinger is not working...
- [ ] Check how much time it spent working;
- [ ] Does it mean that API calls won't prevent the app to fall asleep?
- [ ] The terminal stoped and this is why the app slept?

**Comment by TonGarcia** [comment]
__SOLUTION__: use the new relic.
